# Generated by Django 5.2.4 on 2025-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('IN_PROGRESS', 'В обработке'), ('DONE', 'Завершён')], default='NEW', max_length=20),
        ),
    ]
